Repository cake-tech/cake_wallet, pull requests merged in 2023-05, with the labels that each got.

#911 CW-362 iOS issue keyboard space is still showing in app
  ios/Runner/AppDelegate.swift
Labels: Waiting Tests

#910 Cw 363 back button on receive screen in bright theme is white
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/receive/receive_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
Labels: Ready for Review

#912 CW-368 Range error accessing outputs
  lib/src/screens/send/widgets/confirm_sending_alert.dart
Labels: Ready for Review

#907 CW-260 show amount received for each account
  cw_core/lib/account.dart
  cw_monero/lib/monero_account_list.dart
  lib/monero/cw_monero.dart
  lib/src/screens/monero_accounts/monero_account_list_page.dart
  lib/src/screens/monero_accounts/widgets/account_tile.dart
  lib/view_model/monero_account_list/account_list_item.dart
  lib/view_model/monero_account_list/monero_account_list_view_model.dart
  tool/configure.dart
Labels: Ready for Review

#918 Fix keyboard is not entering text in fields until focus
  lib/src/screens/send/widgets/send_card.dart
Labels: Waiting Tests

#919 CW-376-picker-ui-issue
  lib/src/screens/dashboard/widgets/filter_widget.dart
  lib/src/widgets/check_box_picker.dart
  lib/src/widgets/picker.dart
  lib/src/widgets/picker_wrapper_widget.dart
Labels: Ready for Review, Needs Changes

#924 V4.6.5_V1.3.6
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  ios/Podfile.lock
  ios/Runner/InfoBase.plist
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
  scripts/macos/app_env.sh
Labels: Ready for Review

#920 CW-370-add-options-to-enable-disable-buy-and-sell-actions
  lib/core/backup_service.dart
  lib/entities/main_actions.dart
  lib/entities/preferences_key.dart
  lib/src/screens/settings/privacy_page.dart
  lib/store/settings_store.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/settings/privacy_settings_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#900 CW-254-proper-bitcoin-address-validation-in-exchange-screen
  lib/core/address_validator.dart
  lib/core/validator.dart
  pubspec_base.yaml
Labels: Ready for Review

#931 CW-352 add enable disable screenshot feature to i os
  cw_core/lib/set_app_secure_native.dart
  ios/Runner/AppDelegate.swift
  lib/src/screens/settings/privacy_page.dart
  lib/store/settings_store.dart
Labels: Waiting Tests

#936 CW-388 Add hausa language
  assets/images/flags/hau.png
  lib/entities/language_service.dart
  lib/hausa_intl.dart
  lib/main.dart
  lib/router.dart
  lib/src/screens/dashboard/widgets/menu_widget.dart
  lib/src/screens/settings/desktop_settings/desktop_settings_page.dart
  lib/src/widgets/setting_actions.dart
  res/values/strings_ha.arb
Labels: Needs Changes

#930 CW-379-Investigate-trade-ID-status-updates
  lib/src/screens/anonpay_details/anonpay_details_page.dart
Labels: Ready for Review

#949 New versions 4.6.6 and 1.3.7
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  lib/src/screens/settings/privacy_page.dart
  lib/store/settings_store.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
  scripts/macos/app_env.sh
Labels: Ready for Review, Waiting Tests
