Repository cake-tech/cake_wallet, pull requests merged in 2023-09, with the labels that each got.

#1062 CW-471-Changing-nodes-bug
  lib/src/screens/settings/manage_nodes_page.dart
  lib/view_model/node_list/node_list_view_model.dart
Labels: Waiting Tests

#1070 Fiat api fix
  cw_monero/ios/Classes/monero_api.cpp
  lib/core/fiat_conversion_service.dart
  lib/core/wallet_change_listener_view_model.dart
  lib/di.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/send/send_view_model.dart
  lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
Labels: Ready for Review

#1073 v4.9.0 & v1.6.0
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/src/screens/settings/display_settings_page.dart
  lib/src/screens/support/widgets/support_tiles.dart
  lib/src/widgets/search_bar_widget.dart
  lib/view_model/unspent_coins/unspent_coins_list_view_model.dart
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
  scripts/macos/app_env.sh
Labels: Ready for Review, Waiting Tests

#1076 CW- 463 Fix transaction receive address not showing for Eth/Erc20
  cw_core/lib/transaction_info.dart
  cw_ethereum/lib/ethereum_transaction_info.dart
  cw_ethereum/lib/ethereum_wallet.dart
  lib/exchange/sideshift/sideshift_exchange_provider.dart
  lib/view_model/transaction_details_view_model.dart
Labels: Ready for Review, Waiting Tests

#1083 Generic fixes and enhancements
  android/app/src/main/AndroidManifestBase.xml
  cw_ethereum/lib/ethereum_client.dart
  cw_monero/lib/exceptions/monero_transaction_no_inputs_exception.dart
  cw_monero/lib/monero_wallet.dart
  ios/Podfile.lock
  ios/Runner/InfoBase.plist
  lib/main.dart
  lib/src/screens/dashboard/home_settings_page.dart
  lib/src/screens/root/root.dart
  lib/src/screens/send/send_page.dart
  lib/src/screens/settings/manage_nodes_page.dart
  lib/utils/exception_handler.dart
  lib/view_model/anon_invoice_page_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  pubspec_base.yaml
  scripts/android/app_env.sh
  scripts/android/inject_app_details.sh
  scripts/ios/app_config.sh
Labels: Ready for Review

#1093 v4.9.1_v1.6.1
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  lib/src/screens/restore/restore_options_page.dart
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
  scripts/macos/app_env.sh
Labels: Ready for Review

#1091 Cw linux direct input password build changes
  android/app/build.gradle
  android/build.gradle
  cw_core/lib/root_dir.dart
  cw_haven/android/build.gradle
  cw_haven/lib/haven_wallet.dart
  cw_monero/android/build.gradle
  cw_monero/ios/Classes/monero_api.cpp
  cw_shared_external/android/build.gradle
  lib/entities/default_settings_migration.dart
  lib/ionia/ionia_service.dart
  pubspec_base.yaml
Labels: Ready for Review, Waiting Tests

#1074 CW-442-Update-exchange-selector-checkboxes-with-checkboxes-from-transactions-filter-screen
  lib/src/screens/nodes/widgets/node_form.dart
  lib/src/widgets/check_box_picker.dart
Labels: Ready for Review

#1098 feat: Add TOTP Url link to QR screen
  lib/src/screens/setup_2fa/setup_2fa_qr_page.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#1092 CW-475-Better-error-message-if-there-isnt-enough-network-fee-asset-available
  lib/view_model/send/send_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
  scripts/append_translation.sh
Labels: Ready for Review

#1097 fix: Cake-2FA-setup-issue
  lib/di.dart
  lib/entities/preferences_key.dart
  lib/src/screens/setup_2fa/setup_2fa.dart
  lib/src/screens/setup_2fa/setup_2fa_qr_page.dart
  lib/store/settings_store.dart
  lib/view_model/set_up_2fa_viewmodel.dart
Labels: Waiting Tests
