Repository cake-tech/cake_wallet, pull requests merged in 2023-03, with the labels that each got.

#814 Separate Test APKs
  .github/workflows/pr_test_build.yml
  scripts/android/app_env.sh
Labels: Ready for Review

#794 Error Reports Enhancements
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  cw_core/lib/crypto_currency.dart
  cw_haven/pubspec.yaml
  cw_monero/pubspec.yaml
  lib/reactions/on_authentication_state_change.dart
  lib/utils/exception_handler.dart
  pubspec_base.yaml
Labels: Ready for Review

#810 Add fiat currencies
  assets/images/flags/are.png
  assets/images/flags/arg.png
  assets/images/flags/bgd.png
  assets/images/flags/chl.png
  assets/images/flags/col.png
  assets/images/flags/egy.png
  assets/images/flags/gha.png
  assets/images/flags/gtm.png
  assets/images/flags/irn.png
  assets/images/flags/mar.png
  assets/images/flags/nga.png
  assets/images/flags/twn.png
  assets/images/flags/vnm.png
  lib/entities/fiat_currency.dart
  lib/reactions/on_current_wallet_change.dart
Labels: Waiting Tests

#817 V4.5.9 1.2.8
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
Labels: Ready for Review, Waiting Tests

#821 Fix Exchange Loading issue and Restore wallet
  lib/store/authentication_store.dart
  pubspec_base.yaml
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
Labels: Ready for Review

#822 Update app versions
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
Labels: Ready for Review

#826 Fix payout and input address swap trocador
  lib/exchange/trocador/trocador_exchange_provider.dart
Labels: Waiting Tests

#829 CW-246-Disable-autocorrect-in-Send-address-field-and-make-keyboard-incognito
  lib/src/widgets/address_text_field.dart
Labels: Ready for Review

#827 CW-277-Allow-editing-nodes
  lib/di.dart
  lib/router.dart
  lib/src/screens/nodes/node_create_or_edit_page.dart
  lib/src/screens/nodes/widgets/node_form.dart
  lib/src/screens/settings/connection_sync_page.dart
  lib/view_model/node_list/node_create_or_edit_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#818 CW-243-Better-error-message-for-too-many-decimals
  lib/core/amount_validator.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/exchange/exchange_template_page.dart
  lib/src/screens/receive/widgets/qr_widget.dart
  lib/view_model/send/send_template_view_model.dart
  lib/view_model/send/send_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#834 CW-334-Disable-Auto-validation-for-receive-screen
  lib/core/amount_validator.dart
Labels: Ready for Review

#835 V4.6.0 reports fixes
  cw_core/pubspec.lock
  cw_haven/pubspec.lock
  cw_monero/pubspec.lock
  ios/Podfile.lock
  lib/entities/default_settings_migration.dart
  lib/reactions/bootstrap.dart
  lib/utils/exception_handler.dart
  lib/utils/share_util.dart
Labels: Ready for Review

#840 Fix Create Wallet Seeds screen issue
  lib/di.dart
  lib/reactions/on_authentication_state_change.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/desktop_dashboard_page.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
  lib/utils/exception_handler.dart
  macos/Runner.xcodeproj/project.pbxproj
Labels: Ready for Review

#843 Cw 323 add wallet list to settings on mac
  lib/di.dart
  lib/entities/main_actions.dart
  lib/entities/unstoppable_domain_address.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/new_wallet/new_wallet_page.dart
  lib/src/screens/receive/widgets/qr_widget.dart
  lib/src/screens/root/root.dart
  lib/src/screens/settings/desktop_settings/desktop_settings_page.dart
  lib/src/screens/settings/display_settings_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/src/widgets/setting_actions.dart
  lib/view_model/node_list/node_list_view_model.dart
  lib/view_model/wallet_list/wallet_list_view_model.dart
  macos/Podfile.lock
  pubspec_base.yaml
Labels: Ready for Review

#844 Require pin code on backup and seed/view page
  lib/src/screens/settings/security_backup_page.dart
Labels: Ready for Review

#838 CW-295-Electrum-Transactions-not-getting-fetched-correctly
  cw_bitcoin/lib/electrum.dart
Labels: Ready for Review

#855 CW-340-Truncate-estimated-btc-amount-in-Exchange
  lib/view_model/exchange/exchange_view_model.dart
Labels: Waiting Tests

#859 V4.6.1 report fixes
  lib/anypay/anypay_api.dart
  lib/utils/exception_handler.dart
  lib/utils/share_util.dart
  lib/view_model/order_details_view_model.dart
  lib/view_model/trade_details_view_model.dart
  lib/view_model/transaction_details_view_model.dart
Labels: Ready for Review
