Repository cake-tech/cake_wallet, pull requests merged in 2023-04, with the labels that each got.

#860 Update app versions
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
Labels: Ready for Review, Waiting Tests

#861 Add padding to adjust top
  lib/src/screens/exchange/exchange_template_page.dart
  lib/src/screens/receive/anonpay_invoice_page.dart
Labels: Needs Changes

#870 CW-347-Hide-app-screenshot-from-app-switcher
  android/app/src/main/java/com/cakewallet/cake_wallet/MainActivity.java
  ios/Runner/AppDelegate.swift
Labels: Ready for Review

#875 Fix PR workflow issue
  pubspec_base.yaml
Labels: Ready for Review

#854 CW-338: Currency picker UI when keyboard is showing
  lib/src/screens/exchange/widgets/currency_picker.dart
  lib/src/screens/restore/wallet_restore_from_seed_form.dart
  lib/src/screens/seed_language/widgets/seed_language_picker.dart
  lib/src/widgets/alert_close_button.dart
  lib/src/widgets/picker.dart
  lib/src/widgets/seed_language_selector.dart
Labels: Ready for Review

#876 CW-273-Don't-add-node-under-Advanced-Privacy-Settings-if-it-already-exists
  cw_bitcoin/pubspec.lock
  cw_core/lib/node.dart
  cw_core/pubspec.lock
  cw_monero/pubspec.lock
  lib/src/screens/new_wallet/advanced_privacy_settings_page.dart
  lib/view_model/node_list/node_create_or_edit_view_model.dart
Labels: Needs Changes

#882 CW-350-add-click-to-copy-for-the-exchange-amount-in-the-invoice
  lib/view_model/exchange/exchange_trade_view_model.dart
Labels: Waiting Tests

#872 CW-331-Add-option-to-disable-market-place-in-display-settings
  lib/entities/preferences_key.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/settings/display_settings_page.dart
  lib/store/settings_store.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/settings/display_settings_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_zh.arb
Labels: Needs Changes

#864 CW-33 Add app review after successful transactions and exchange
  lib/entities/preferences_key.dart
  lib/src/screens/exchange_trade/exchange_trade_page.dart
  lib/src/screens/send/send_page.dart
  lib/utils/request_review_handler.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  pubspec_base.yaml
Labels: Ready for Review

#887 Cw 304 enhance talkback
  lib/src/screens/base_page.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/new_wallet/new_wallet_page.dart
  lib/src/screens/pin_code/pin_code_widget.dart
  lib/src/screens/receive/receive_page.dart
  lib/src/screens/receive/widgets/address_cell.dart
  lib/src/screens/settings/connection_sync_page.dart
  lib/src/widgets/introducing_card.dart
Labels: Waiting Tests

#886 CW-278 Enhance PIN timeout feature code
  lib/core/auth_service.dart
  lib/di.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_wallet_selection_dropdown.dart
  lib/src/screens/settings/security_backup_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
Labels: Ready for Review

#868 Cw 262 better handle user exchange amount below minimum or maximum trade size
  lib/core/amount_validator.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/view_model/exchange/exchange_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#885 CW-351-Add-option-in-Privacy-settings-to-enable-disable-screenshots
  android/app/src/main/java/com/cakewallet/cake_wallet/MainActivity.java
  cw_core/lib/set_app_secure_native.dart
  cw_monero/example/pubspec.lock
  lib/core/backup_service.dart
  lib/entities/preferences_key.dart
  lib/src/screens/settings/privacy_page.dart
  lib/store/settings_store.dart
  lib/view_model/settings/privacy_settings_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#846 CW-325-Coin-Control-enhancements
  cw_bitcoin/lib/electrum_balance.dart
  cw_bitcoin/lib/electrum_wallet.dart
  cw_bitcoin/lib/electrum_wallet_snapshot.dart
  cw_core/lib/unspent_coins_info.dart
  cw_core/lib/wallet_base.dart
  cw_haven/lib/haven_wallet.dart
  cw_monero/lib/monero_wallet.dart
  lib/src/screens/dashboard/widgets/balance_page.dart
  lib/src/screens/unspent_coins/unspent_coins_details_page.dart
  lib/src/screens/unspent_coins/widgets/unspent_coins_list_item.dart
  lib/view_model/dashboard/balance_view_model.dart
  lib/view_model/unspent_coins/unspent_coins_details_view_model.dart
  lib/view_model/unspent_coins/unspent_coins_item.dart
  lib/view_model/unspent_coins/unspent_coins_list_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#880 CW-344-Exchanging-TO-the-current-wallet-currency-should-allow-changing-the-address
  lib/src/screens/contact/contact_list_page.dart
  lib/src/screens/exchange/widgets/exchange_card.dart
Labels: Waiting Tests

#890 Add btcln; add 2 assets to SideShift
  cw_core/lib/crypto_currency.dart
  lib/core/address_validator.dart
  lib/exchange/sideshift/sideshift_exchange_provider.dart
  lib/exchange/trocador/trocador_exchange_provider.dart
Labels: Ready for Review

#878 CW-289-Fix bitcoin pending send receive transactions not showing until confirmed
  cw_bitcoin/lib/electrum.dart
  cw_bitcoin/lib/electrum_transaction_info.dart
  cw_bitcoin/lib/electrum_wallet.dart
Labels: Ready for Review

#863 CW-59-New-update-highlight-popup
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  lib/di.dart
  lib/entities/default_settings_migration.dart
  lib/entities/preferences_key.dart
  lib/main.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/desktop_dashboard_page.dart
  lib/src/screens/dashboard/widgets/filter_widget.dart
  lib/src/screens/monero_accounts/monero_account_list_page.dart
  lib/src/screens/release_notes/release_notes_screen.dart
  lib/src/screens/seed_language/widgets/seed_language_picker.dart
  lib/src/widgets/alert_close_button.dart
  lib/utils/version_comparator.dart
  lib/view_model/dashboard/dashboard_view_model.dart
Labels: Needs Changes

#877 CW-240 Receive fiat currency amount and receive animations
  lib/core/amount_validator.dart
  lib/di.dart
  lib/entities/qr_view_data.dart
  lib/router.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/receive/anonpay_receive_page.dart
  lib/src/screens/receive/fullscreen_qr_page.dart
  lib/src/screens/receive/receive_page.dart
  lib/src/screens/receive/widgets/currency_input_field.dart
  lib/src/screens/receive/widgets/qr_widget.dart
  lib/src/screens/wallet_keys/wallet_keys_page.dart
  lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
Labels: Ready for Review

#893 V4.6.3_1.3.3
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  cw_core/lib/balance.dart
  lib/view_model/dashboard/balance_view_model.dart
  lib/view_model/restore/wallet_restore_from_qr_code.dart
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
  scripts/macos/app_env.sh
Labels: Ready for Review, Waiting Tests
