Repository cake-tech/cake_wallet, pull requests merged in 2023-07, with the labels that each got.

#976 CW-417-Additional-callouts
  lib/src/screens/dashboard/widgets/balance_page.dart
  lib/src/screens/dashboard/widgets/market_place_page.dart
  lib/src/screens/dashboard/widgets/transactions_page.dart
  lib/src/screens/exchange_trade/exchange_trade_page.dart
  lib/src/screens/exchange_trade/information_page.dart
  lib/src/screens/ionia/cards/ionia_buy_card_detail_page.dart
  lib/src/screens/ionia/cards/ionia_debit_card_page.dart
  lib/src/screens/ionia/cards/ionia_gift_card_detail_page.dart
  lib/src/widgets/dashboard_card_widget.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#979 CW-424-ChangeNOW-add-payload-details
  lib/exchange/changenow/changenow_exchange_provider.dart
  lib/utils/distribution_info.dart
  lib/view_model/exchange/exchange_trade_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/trade_details_view_model.dart
Labels: Ready for Review

#968 CW-427-Refactor-wallet-type-selection-UI
  cw_core/lib/wallet_type.dart
  lib/src/screens/new_wallet/new_wallet_type_page.dart
  lib/src/screens/new_wallet/widgets/select_button.dart
  lib/src/widgets/picker.dart
  lib/src/widgets/search_bar_widget.dart
Labels: Ready for Review

#939 Cw 372 improve monero haven account selection picker
  lib/src/screens/monero_accounts/monero_account_list_page.dart
  lib/src/screens/monero_accounts/widgets/account_tile.dart
  lib/src/widgets/picker_inner_wrapper_widget.dart
Labels: Ready for Review

#921 CW-349 MacOS UI issue when navigating to Transaction details screen
  lib/src/screens/dashboard/desktop_widgets/desktop_dashboard_actions.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
  lib/src/screens/dashboard/widgets/balance_page.dart
  lib/src/screens/new_wallet/advanced_privacy_settings_page.dart
  lib/src/screens/nodes/node_create_or_edit_page.dart
  lib/store/settings_store.dart
  lib/view_model/dashboard/desktop_sidebar_view_model.dart
  macos/Podfile.lock
Labels: Needs Changes

#994 Disable Cake Pay Mobile
  lib/src/screens/dashboard/widgets/balance_page.dart
  lib/src/screens/dashboard/widgets/market_place_page.dart
  lib/utils/feature_flag.dart
Labels: Ready for Review

#945 CW-214-Monero-wallet-rescan-bug
  cw_bitcoin/lib/electrum_transaction_history.dart
  cw_core/lib/transaction_history.dart
  cw_monero/lib/monero_transaction_history.dart
  lib/view_model/rescan_view_model.dart
Labels: Ready for Review

#913 Cw 355 more talkback unlabeled
  lib/src/screens/base_page.dart
  lib/src/screens/contact/contact_list_page.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
  lib/src/screens/new_wallet/new_wallet_page.dart
  lib/src/screens/pin_code/pin_code_widget.dart
  lib/src/screens/receive/receive_page.dart
  lib/src/screens/receive/widgets/address_cell.dart
  lib/src/screens/send/send_page.dart
  lib/src/widgets/address_text_field.dart
  lib/src/widgets/introducing_card.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#974 Cw 426 replace trash and swipe with edit icons
  cw_bitcoin/lib/bitcoin_wallet_service.dart
  cw_bitcoin/lib/electrum_transaction_history.dart
  cw_bitcoin/lib/electrum_wallet.dart
  cw_bitcoin/lib/litecoin_wallet_service.dart
  cw_core/lib/wallet_service.dart
  cw_haven/lib/haven_wallet.dart
  cw_haven/lib/haven_wallet_service.dart
  cw_monero/lib/monero_wallet.dart
  cw_monero/lib/monero_wallet_service.dart
  lib/core/key_service.dart
  lib/core/wallet_loading_service.dart
  lib/di.dart
  lib/router.dart
  lib/routes.dart
  lib/src/screens/nodes/node_create_or_edit_page.dart
  lib/src/screens/nodes/widgets/node_indicator.dart
  lib/src/screens/nodes/widgets/node_list_row.dart
  lib/src/screens/settings/connection_sync_page.dart
  lib/src/screens/wallet/wallet_edit_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/src/widgets/standard_list.dart
  lib/view_model/wallet_list/wallet_edit_view_model.dart
  lib/view_model/wallet_list/wallet_list_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#977 Cw 430 find a better way to decide when to show the desktop UI
  android/app/src/main/AndroidManifestBase.xml
  lib/main.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/widgets/present_receive_option_picker.dart
  lib/src/screens/receive/anonpay_invoice_page.dart
  lib/src/screens/receive/anonpay_receive_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/utils/responsive_layout_util.dart
Labels: Waiting Tests

#978 Fix Bitcoin transactions not showing
  cw_bitcoin/lib/electrum.dart
Labels: Ready for Review

#998 Update app versions
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  ios/Podfile.lock
  lib/utils/exception_handler.dart
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
  scripts/macos/app_env.sh
Labels: Ready for Review, Waiting Tests

#1009 Free Up GitHub Actions Ubuntu Runner Disk Space
  .github/workflows/pr_test_build.yml
  lib/utils/exception_handler.dart
Labels: Ready for Review

#1012 CW-443 Use networkWallets on OnRamper
  lib/buy/onramper/onramper_buy_provider.dart
Labels: Ready for Review

#1005 CW-441 xmr price issue
  lib/reactions/fiat_rate_update.dart
  lib/view_model/dashboard/balance_view_model.dart
Labels: Ready for Review

#1010 fix nav-bar issue
  lib/src/widgets/nav_bar.dart
Labels: Waiting Tests
