Repository cake-tech/cake_wallet, pull requests merged in 2023-06, with the labels that each got.

#952 CW-407 Revert changing Nigeria Flag name
  assets/images/flags/nga.png
  lib/entities/language_service.dart
Labels: Waiting Tests

#956 Fixed 2FA related French localization
  res/values/strings_fr.arb
Labels: Ready for Review

#955 Fixes for v4.6.6
  res/values/strings_fr.arb
Labels: Ready for Review

#943 CW-400 investigate cupertino nav bar null exception
  lib/di.dart
  lib/router.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_dashboard_actions.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/dashboard/widgets/market_place_page.dart
  lib/src/screens/ionia/auth/ionia_welcome_page.dart
  lib/src/screens/ionia/cards/ionia_manage_cards_page.dart
  lib/src/screens/receive/anonpay_invoice_page.dart
  lib/src/screens/restore/wallet_restore_page.dart
  lib/view_model/dashboard/market_place_view_model.dart
  lib/view_model/ionia/ionia_gift_cards_list_view_model.dart
Labels: Waiting Tests

#959 CW-411 Update sideshift api
  .github/workflows/pr_test_build.yml
  lib/exchange/sideshift/sideshift_exchange_provider.dart
  lib/view_model/exchange/exchange_trade_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  tool/utils/secret_key.dart
Labels: Ready for Review, Needs Changes

#926 Cw 231 display balance in send and transaction screens when long pressing and when show balance is disabled
  lib/src/screens/dashboard/widgets/transactions_page.dart
  lib/src/screens/send/send_page.dart
  lib/view_model/dashboard/transaction_list_item.dart
Labels: Ready for Review

#935 CW-383-replace-swipe-to-delete-wallet-action-with-a-delete-trash-icon-on-the-right
  lib/src/screens/wallet_list/wallet_list_page.dart
Labels: Ready for Review

#958 CW-342 Enable Mac Layout on iPad
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x 1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x 1.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/di.dart
  lib/entities/main_actions.dart
  lib/main.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/dashboard/widgets/balance_page.dart
  lib/src/screens/dashboard/widgets/transactions_page.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/receive/anonpay_invoice_page.dart
  lib/src/screens/receive/widgets/currency_input_field.dart
  lib/src/screens/send/send_page.dart
  lib/src/screens/send/widgets/send_card.dart
  lib/src/screens/settings/display_settings_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/src/widgets/add_template_button.dart
  lib/src/widgets/address_text_field.dart
  lib/utils/exception_handler.dart
  lib/utils/responsive_layout_util.dart
Labels: Waiting Tests, Needs Changes

#964 CW-398-MoonPay-offramp-(Sell)-improvements
  lib/buy/moonpay/moonpay_buy_provider.dart
  lib/di.dart
  lib/entities/main_actions.dart
  lib/router.dart
  lib/routes.dart
  lib/src/screens/buy/webview_page.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#957 CW-395-Trade-ID-status-not-updating-in-trade-details-screen
  lib/exchange/changenow/changenow_exchange_provider.dart
  lib/view_model/trade_details_view_model.dart
Labels: Ready for Review

#971 V4.6.7 v1.3.8
  assets/text/Monerocom_Release_Notes.txt
  assets/text/Release_Notes.txt
  lib/di.dart
  lib/entities/main_actions.dart
  lib/router.dart
  lib/routes.dart
  lib/src/screens/buy/payfura_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
  scripts/macos/app_env.sh
Labels: Ready for Review, Waiting Tests
