Repository cake-tech/cake_wallet, pull requests merged in 2023-08, with the labels that each got.

#1004 CW-425 use the open alias new line UI
  lib/entities/openalias_record.dart
  lib/entities/parsed_address.dart
  lib/src/screens/send/widgets/extract_address_from_parsed.dart
  lib/src/screens/send/widgets/send_card.dart
  lib/src/widgets/address_text_field.dart
  lib/view_model/send/output.dart
  pubspec_base.yaml
Labels: Ready for Review

#1013 CW-423 Use SensitiveClipboard for sensitive Stings
  android/app/build.gradle
  lib/src/screens/backup/backup_page.dart
  lib/src/screens/seed/pre_seed_page.dart
  lib/src/screens/seed/wallet_seed_page.dart
  lib/src/screens/setup_2fa/setup_2fa_qr_page.dart
  lib/src/screens/wallet_keys/wallet_keys_page.dart
  lib/utils/clipboard_util.dart
  pubspec_base.yaml
Labels: Needs Changes

#995 Cw 433 support send templates with multiple recipients
  lib/entities/template.dart
  lib/src/screens/send/send_page.dart
  lib/src/screens/send/send_template_page.dart
  lib/src/screens/send/widgets/send_template_card.dart
  lib/src/widgets/template_tile.dart
  lib/store/templates/send_template_store.dart
  lib/view_model/send/send_template_view_model.dart
  lib/view_model/send/template_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#966 CW-224-Allow-Monero-proxy-in-node-settings
  cw_core/lib/node.dart
  cw_haven/lib/api/signatures.dart
  cw_haven/lib/api/types.dart
  cw_haven/lib/api/wallet.dart
  cw_haven/lib/haven_wallet.dart
  cw_monero/ios/Classes/monero_api.cpp
  cw_monero/lib/api/signatures.dart
  cw_monero/lib/api/types.dart
  cw_monero/lib/api/wallet.dart
  cw_monero/lib/monero_wallet.dart
  lib/core/socks_proxy_node_address_validator.dart
  lib/src/screens/nodes/widgets/node_form.dart
  lib/view_model/node_list/node_create_or_edit_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#1008 CW-392 Allow Users to rename Monero and Haven accounts
  lib/src/screens/monero_accounts/widgets/account_tile.dart
Labels: Ready for Review

#1007 feat: Introduce QR Scanning to add new node
  lib/src/screens/nodes/node_create_or_edit_page.dart
  lib/src/screens/nodes/widgets/node_form.dart
  lib/view_model/node_list/node_create_or_edit_view_model.dart
Labels: Ready for Review

#967 CW-266 verbose access controls for TOTP 2FA
  .gitignore
  android/gradle.properties
  lib/core/auth_service.dart
  lib/core/backup_service.dart
  lib/di.dart
  lib/entities/cake_2fa_preset_options.dart
  lib/entities/preferences_key.dart
  lib/src/screens/contact/contact_list_page.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_wallet_selection_dropdown.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/root/root.dart
  lib/src/screens/send/send_page.dart
  lib/src/screens/settings/security_backup_page.dart
  lib/src/screens/settings/widgets/settings_choices_cell.dart
  lib/src/screens/setup_2fa/modify_2fa_page.dart
  lib/src/screens/setup_2fa/setup_2fa.dart
  lib/src/screens/setup_2fa/setup_2fa_enter_code_page.dart
  lib/src/screens/wallet/wallet_edit_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/store/settings_store.dart
  lib/view_model/contact_list/contact_list_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/send/send_view_model.dart
  lib/view_model/set_up_2fa_viewmodel.dart
  lib/view_model/settings/security_settings_view_model.dart
  lib/view_model/wallet_list/wallet_list_view_model.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#1020 CW-450 Add version code & version name to android configs
  android/app/src/main/AndroidManifestBase.xml
  scripts/android/inject_app_details.sh
Labels: Ready for Review

#1014 Cw 155 monero synchronization
  cw_core/lib/set_app_secure_native.dart
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/InfoBase.plist
  lib/core/backup_service.dart
  lib/di.dart
  lib/entities/background_tasks.dart
  lib/entities/load_current_wallet.dart
  lib/entities/preferences_key.dart
  lib/main.dart
  lib/router.dart
  lib/routes.dart
  lib/src/screens/settings/connection_sync_page.dart
  lib/src/screens/settings/manage_nodes_page.dart
  lib/src/screens/settings/other_settings_page.dart
  lib/src/widgets/standard_list.dart
  lib/store/settings_store.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/settings/choices_list_item.dart
  lib/view_model/settings/sync_mode.dart
  lib/view_model/wallet_creation_vm.dart
  lib/view_model/wallet_list/wallet_list_view_model.dart
  pubspec_base.yaml
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#1026 feat: Replace buy action to use onramper
  lib/entities/main_actions.dart
  lib/src/screens/dashboard/dashboard_page.dart
Labels: Ready for Review

#1017 Update UD domains
  lib/entities/parse_address_from_domain.dart
Labels: Ready for Review

#1048 Flutter update
  .github/workflows/cache_dependencies.yml
  .github/workflows/pr_test_build.yml
  android/build.gradle
  cw_bitcoin/pubspec.yaml
  cw_core/pubspec.yaml
  cw_ethereum/lib/ethereum_client.dart
  cw_ethereum/pubspec.yaml
  cw_haven/pubspec.yaml
  cw_monero/pubspec.yaml
  cw_shared_external/pubspec.yaml
  howto-build-android.md
  lib/core/generate_wallet_password.dart
  lib/locales/hausa_intl.dart
  lib/locales/yoruba_intl.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/restore/widgets/restore_button.dart
  lib/src/screens/seed/pre_seed_page.dart
  lib/src/screens/send/send_page.dart
  lib/src/screens/send/widgets/send_card.dart
  lib/src/screens/settings/widgets/settings_choices_cell.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/src/widgets/standard_list.dart
  pubspec_base.yaml
  tool/append_translation.dart
  tool/localization/localization_constants.dart
Labels: Ready for Review, Waiting Tests

#1051 Fix Ethereum network for anonpay invoice
  lib/anonpay/anonpay_api.dart
  lib/src/screens/receive/anonpay_invoice_page.dart
Labels: Waiting Tests

#1052 Cw 470 additional theming fixes
  lib/buy/onramper/onramper_buy_provider.dart
  lib/entities/main_actions.dart
  lib/src/screens/backup/backup_page.dart
  lib/src/screens/contact/contact_list_page.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/dashboard/widgets/balance_page.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/widgets/search_bar_widget.dart
  lib/themes/extensions/picker_theme.dart
  lib/themes/high_contrast_theme.dart
  lib/themes/theme_base.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#1056 fix: Rotate TOTP Secret
  lib/view_model/set_up_2fa_viewmodel.dart
Labels: Ready for Review

#1055 Add restore from private key to Ethereum
  cw_core/lib/wallet_base.dart
  cw_ethereum/lib/ethereum_wallet.dart
  cw_ethereum/lib/ethereum_wallet_creation_credentials.dart
  cw_ethereum/lib/ethereum_wallet_service.dart
  ios/Podfile.lock
  lib/di.dart
  lib/ethereum/cw_ethereum.dart
  lib/router.dart
  lib/routes.dart
  lib/src/screens/restore/restore_wallet_from_seed_details.dart
  lib/src/screens/restore/wallet_restore_from_keys_form.dart
  lib/src/screens/restore/wallet_restore_page.dart
  lib/src/widgets/seed_widget.dart
  lib/utils/exception_handler.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/restore/restore_from_qr_vm.dart
  lib/view_model/restore/restore_wallet.dart
  lib/view_model/restore/wallet_restore_from_qr_code.dart
  lib/view_model/wallet_keys_view_model.dart
  lib/view_model/wallet_restoration_from_keys_vm.dart
  lib/view_model/wallet_restoration_from_seed_vm.dart
  lib/view_model/wallet_restore_view_model.dart
  lib/view_model/wallet_seed_view_model.dart
  tool/configure.dart
Labels: Ready for Review

#902 CW-228 Auto generate monero subaddress
  cw_core/lib/address_info.dart
  cw_core/lib/hive_type_ids.dart
  cw_core/lib/wallet_addresses.dart
  cw_core/lib/wallet_base.dart
  cw_core/lib/wallet_info.dart
  cw_haven/lib/haven_wallet.dart
  cw_monero/lib/monero_subaddress_list.dart
  cw_monero/lib/monero_wallet.dart
  cw_monero/lib/monero_wallet_addresses.dart
  lib/core/backup_service.dart
  lib/di.dart
  lib/entities/auto_generate_subaddress_status.dart
  lib/entities/preferences_key.dart
  lib/main.dart
  lib/reactions/on_current_wallet_change.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/monero_accounts/widgets/account_tile.dart
  lib/src/screens/restore/restore_options_page.dart
  lib/src/screens/restore/widgets/backup_file_button.dart
  lib/src/screens/settings/privacy_page.dart
  lib/store/settings_store.dart
  lib/view_model/contact_list/contact_list_view_model.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/settings/privacy_settings_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
  tool/append_translation.dart
  tool/translation_consistence.dart
  tool/utils/translation/arb_file_utils.dart
  tool/utils/translation/translation_constants.dart
  tool/utils/translation/translation_utils.dart
Labels: Ready for Review

#1059 Fix Wallet Loading issues (basic_string & input_stream)
  .github/workflows/cache_dependencies.yml
  cw_monero/lib/monero_wallet_service.dart
  cw_monero/macos/Classes/monero_api.cpp
  lib/entities/default_settings_migration.dart
  macos/Podfile.lock
Labels: Ready for Review, Waiting Tests
