Repository cake-tech/cake_wallet, pull requests merged in 2023-02, with the labels that each got.

#743 CW-287 get address from twitter bio
  .github/workflows/pr_test_build.yml
  lib/core/address_validator.dart
  lib/entities/openalias_record.dart
  lib/entities/parse_address_from_domain.dart
  lib/entities/parsed_address.dart
  lib/src/screens/send/widgets/extract_address_from_parsed.dart
  lib/twitter/twitter_api.dart
  lib/twitter/twitter_user.dart
  res/values/strings_ar.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_zh.arb
  tool/utils/secret_key.dart
Labels: Ready for Review

#755 Avoid reporting user errors
  lib/main.dart
  lib/utils/exception_handler.dart
Labels: Ready for Review

#746 update cake pay checkout wording for bitcoin only
  lib/src/screens/ionia/cards/ionia_payment_status_page.dart
  lib/src/screens/send/widgets/extract_address_from_parsed.dart
  lib/view_model/ionia/ionia_payment_status_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_zh.arb
Labels: Waiting Tests

#757 Add LTC to twitter address parsing
  lib/core/address_validator.dart
Labels: Ready for Review

#758 V4.5.7 v1.2.6
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
Labels: Ready for Review

#767 Users Reports Fixes
  .github/workflows/pr_test_build.yml
  analysis_options.yaml
  cw_bitcoin/pubspec.lock
  cw_core/pubspec.lock
  cw_haven/pubspec.lock
  cw_monero/pubspec.lock
  lib/entities/preferences_key.dart
  lib/router.dart
  lib/src/screens/dashboard/widgets/address_page.dart
  lib/src/screens/exchange_trade/exchange_trade_page.dart
  lib/src/screens/receive/receive_page.dart
  lib/src/screens/seed/wallet_seed_page.dart
  lib/src/screens/send/send_page.dart
  lib/src/screens/settings/connection_sync_page.dart
  lib/src/screens/wallet_list/wallet_menu.dart
  lib/src/screens/wallet_list/wallet_menu_item.dart
  lib/src/screens/wallet_list/widgets/wallet_menu_alert.dart
  lib/utils/exception_handler.dart
  lib/utils/share_util.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
Labels: Ready for Review

#772 New Release versions
  scripts/android/app_env.sh
  scripts/ios/app_env.sh
Labels: Ready for Review

#776 Allow Keyboard usage on PIN screen
  lib/src/screens/pin_code/pin_code_widget.dart
  lib/src/widgets/nav_bar.dart
Labels: Ready for Review

#779 Add Marketplace to dashboard view
  lib/router.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_dashboard_actions.dart
  lib/src/widgets/market_place_item.dart
Labels: Ready for Review

#774 [CW-310] Add constraints to images on macos
  lib/src/screens/new_wallet/new_wallet_page.dart
  lib/src/screens/new_wallet/new_wallet_type_page.dart
  lib/src/screens/pin_code/pin_code_widget.dart
  lib/utils/responsive_layout_util.dart
Labels: Waiting Tests

#773 add address lookup for pinned tweet
  lib/entities/parse_address_from_domain.dart
  lib/twitter/twitter_api.dart
  lib/twitter/twitter_user.dart
Labels: Ready for Review

#770 add number of confirmations to transactions
  cw_haven/lib/haven_transaction_info.dart
  cw_monero/lib/monero_transaction_info.dart
  lib/src/screens/dashboard/widgets/transaction_raw.dart
  lib/src/screens/dashboard/widgets/transactions_page.dart
  lib/view_model/dashboard/transaction_list_item.dart
Labels: Ready for Review

#786 MacOS settings icon to be a toggle
  lib/di.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/src/screens/dashboard/desktop_dashboard_page.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_sidebar/side_menu.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_sidebar/side_menu_item.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
  lib/src/screens/settings/desktop_settings/dashboard_settings_page.dart
  lib/view_model/dashboard/desktop_sidebar_view_model.dart
Labels: Waiting Tests

#788 Fix incorrect amount parsing
  cw_bitcoin/lib/bitcoin_amount_format.dart
  cw_core/lib/monero_amount_format.dart
Labels: Ready for Review

#802 Add app lock feature on mac
  lib/src/screens/dashboard/desktop_widgets/desktop_sidebar/side_menu_item.dart
  lib/src/screens/dashboard/desktop_widgets/desktop_sidebar_wrapper.dart
  lib/view_model/dashboard/desktop_sidebar_view_model.dart
Labels: Waiting Tests

#783 Fix Share issue on iPad
  lib/src/screens/backup/backup_page.dart
  lib/src/screens/dashboard/dashboard_page.dart
  lib/utils/exception_handler.dart
  lib/utils/share_util.dart
Labels: Ready for Review

#784 Fix Support links
  lib/src/screens/settings/widgets/settings_link_provider_cell.dart
  lib/view_model/support_view_model.dart
Labels: Ready for Review, Waiting Tests
