Repository cake-tech/cake_wallet, pull requests merged in 2024-09, with the labels that each got.

#1651 CW-695: Fix Zone Mismatch Error Triggered By Restoring Backup
  lib/main.dart
  lib/view_model/restore_from_backup_view_model.dart
Labels: Waiting Tests

#1575 Cw 682 integrate stealth ex exchange provider
  .github/workflows/pr_test_build_android.yml
  .github/workflows/pr_test_build_linux.yml
  assets/images/stealthex.png
  lib/exchange/exchange_provider_description.dart
  lib/exchange/provider/stealth_ex_exchange_provider.dart
  lib/exchange/trade_state.dart
  lib/store/dashboard/trade_filter_store.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/exchange/exchange_trade_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/trade_details_view_model.dart
  tool/utils/secret_key.dart
Labels: Ready for Review, Waiting Tests

#1562 Integrate LetsExchange exchange provider
  .github/workflows/pr_test_build_android.yml
  .github/workflows/pr_test_build_linux.yml
  assets/images/letsexchange_icon.svg
  lib/exchange/exchange_provider_description.dart
  lib/exchange/provider/letsexchange_exchange_provider.dart
  lib/exchange/provider/stealth_ex_exchange_provider.dart
  lib/exchange/trade_state.dart
  lib/src/screens/dashboard/widgets/trade_row.dart
  lib/src/screens/exchange_trade/exchange_confirm_page.dart
  lib/store/dashboard/trade_filter_store.dart
  lib/utils/image_utill.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/trade_details_view_model.dart
  tool/utils/secret_key.dart
Labels: Ready for Review

#1663 feat: Add warning before adding erc20 token via contract address
  .github/workflows/pr_test_build_android.yml
  .github/workflows/pr_test_build_linux.yml
  lib/entities/erc20_token_info_explorers.dart
  lib/entities/erc20_token_info_moralis.dart
  lib/src/screens/dashboard/edit_token_page.dart
  lib/view_model/dashboard/home_settings_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
  tool/utils/secret_key.dart
Labels: Waiting Tests

#1676 do not restore deterministic wallet if it's not one
  cw_monero/lib/api/wallet_manager.dart
  cw_wownero/lib/api/wallet_manager.dart
Labels: Waiting Tests

#1630 CW-611-Refactor-Address-Handling
  cw_bitcoin/lib/electrum_wallet.dart
  cw_bitcoin/lib/electrum_wallet_addresses.dart
  cw_core/lib/subaddress.dart
  cw_core/lib/wallet_addresses.dart
  cw_core/lib/wallet_info.dart
  cw_haven/lib/haven_wallet_addresses.dart
  cw_monero/lib/api/subaddress_list.dart
  cw_monero/lib/api/transaction_history.dart
  cw_monero/lib/api/wallet.dart
  cw_monero/lib/monero_subaddress_list.dart
  cw_monero/lib/monero_wallet.dart
  cw_monero/lib/monero_wallet_addresses.dart
  cw_wownero/lib/api/subaddress_list.dart
  cw_wownero/lib/api/transaction_history.dart
  cw_wownero/lib/api/wallet.dart
  cw_wownero/lib/wownero_subaddress_list.dart
  cw_wownero/lib/wownero_wallet.dart
  cw_wownero/lib/wownero_wallet_addresses.dart
  lib/monero/cw_monero.dart
  lib/src/screens/dashboard/pages/address_page.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/exchange/exchange_template_page.dart
  lib/src/screens/receive/receive_page.dart
  lib/src/screens/receive/widgets/address_cell.dart
  lib/src/screens/receive/widgets/address_list.dart
  lib/src/screens/receive/widgets/header_tile.dart
  lib/src/screens/receive/widgets/qr_widget.dart
  lib/view_model/contact_list/contact_list_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/wallet_address_list/wallet_address_edit_or_create_view_model.dart
  lib/view_model/wallet_address_list/wallet_address_hidden_list_header.dart
  lib/view_model/wallet_address_list/wallet_address_list_item.dart
  lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
  res/values/strings_en.arb
  tool/configure.dart
Labels: Waiting Tests
