Repository cake-tech/cake_wallet, pull requests merged in 2025-01, with the labels that each got.

#1967 Cw 903 new screens for new shared seed wallets
  lib/router.dart
  lib/routes.dart
  lib/src/screens/new_wallet/new_wallet_page.dart
  lib/src/screens/new_wallet/wallet_group_description_page.dart
  lib/src/screens/new_wallet/wallet_group_display_page.dart
  lib/src/screens/new_wallet/wallet_group_existing_seed_description_page.dart
  lib/themes/extensions/theme_type_images.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_vi.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#1939 Cw 897 stable coins exchanges rate issue
  lib/exchange/provider/letsexchange_exchange_provider.dart
  lib/exchange/provider/sideshift_exchange_provider.dart
  lib/exchange/provider/trocador_exchange_provider.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/view_model/exchange/exchange_view_model.dart
Labels: Ready for Review

#1961 Cw 865 create new seed UI for show seed keys page to match onboarding seed verification UI
  lib/src/screens/seed/wallet_seed_page.dart
  lib/src/screens/wallet_keys/wallet_keys_page.dart
  lib/src/widgets/seedphrase_grid_widget.dart
  lib/src/widgets/text_info_box.dart
  lib/src/widgets/warning_box_widget.dart
  lib/view_model/wallet_keys_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_vi.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Ready for Review

#1987 Improve Error Handling
  cw_core/lib/exceptions.dart
  cw_zano/lib/zano_wallet_exceptions.dart
  lib/src/screens/restore/wallet_restore_page.dart
  lib/view_model/wallet_creation_vm.dart
Labels: Work in Progress

#1957 CW-898 fix fast scanner
  lib/view_model/node_list/node_create_or_edit_view_model.dart
  pubspec_base.yaml
Labels: Waiting Tests

#1989 Keep drawer opened
  lib/src/screens/settings/desktop_settings/desktop_settings_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/src/widgets/setting_actions.dart
Labels: Waiting Tests
