Repository cake-tech/cake_wallet, pull requests merged in 2025-05, with the labels that each got.

#2214 fix(cw_monero): prevent monero wallet from breaking during rename
  cw_decred/lib/wallet.dart
  cw_decred/lib/wallet_service.dart
  cw_monero/lib/api/account_list.dart
  cw_monero/lib/api/coins_info.dart
  cw_monero/lib/api/subaddress_list.dart
  cw_monero/lib/api/transaction_history.dart
  cw_monero/lib/api/wallet.dart
  cw_monero/lib/api/wallet_manager.dart
  cw_monero/lib/ledger.dart
  cw_monero/lib/monero_account_list.dart
  cw_monero/lib/monero_unspent.dart
  cw_monero/lib/monero_wallet.dart
  cw_monero/lib/monero_wallet_service.dart
  cw_monero/pubspec.lock
  cw_monero/pubspec.yaml
  cw_wownero/pubspec.lock
  cw_wownero/pubspec.yaml
  cw_zano/pubspec.lock
  cw_zano/pubspec.yaml
  ios/Podfile.lock
  lib/core/wallet_loading_service.dart
  lib/monero/cw_monero.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/send/send_view_model.dart
  scripts/prepare_moneroc.sh
Labels: Waiting Tests

#2255 fix: selection of the wordlist for seed validation on the restore from seed page
  lib/src/screens/restore/wallet_restore_from_seed_form.dart
Labels: Ready for Review

#2280 misc-seed-page-fixes
  lib/src/screens/restore/wallet_restore_from_seed_form.dart
  lib/src/widgets/seed_widget.dart
Labels: Ready for Review

#2278 CW-1045-Ledger-Bugs-Enhancements
  cw_monero/lib/api/wallet_manager.dart
  cw_monero/lib/ledger.dart
  cw_monero/lib/monero_wallet.dart
  cw_monero/lib/monero_wallet_service.dart
  cw_monero/pubspec.lock
  cw_monero/pubspec.yaml
  cw_wownero/pubspec.lock
  cw_wownero/pubspec.yaml
  cw_zano/pubspec.lock
  cw_zano/pubspec.yaml
  lib/monero/cw_monero.dart
  lib/src/screens/connect_device/connect_device_page.dart
  lib/src/screens/send/send_page.dart
  lib/src/widgets/bottom_sheet/info_steps_bottom_sheet_widget.dart
  lib/view_model/send/send_view_model.dart
  lib/view_model/send/send_view_model_state.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_vi.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
  scripts/prepare_moneroc.sh
  tool/configure.dart
Labels: Work in Progress
