Repository cake-tech/cake_wallet, pull requests merged in 2025-04, with the labels that each got.

#2140 Adopt bottom-sheet send flow for ledger
  lib/src/screens/send/send_page.dart
  lib/view_model/send/send_view_model.dart
Labels: Waiting Tests

#2152 Show correct title when reconnecting to your ledger device
  lib/router.dart
  lib/src/screens/connect_device/connect_device_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
Labels: Ready for Review

#1940 Skip onramper transaction page and go directly to provider
  assets/node_list.yml
  lib/buy/onramper/onramper_buy_provider.dart
Labels: Waiting Tests

#2131 CW-723-Add-Monero-support-to-the-Shared-Seed-feature-in-Cake
  .github/workflows/pr_test_build_linux.yml
  cw_monero/.gitignore
  cw_monero/lib/api/wallet.dart
  cw_monero/lib/bip39_seed.dart
  cw_monero/lib/monero_wallet_service.dart
  cw_monero/pubspec.lock
  cw_monero/pubspec.yaml
  cw_monero/test/bip39_seed_test.dart
  cw_monero/test/mock/path_provider.dart
  cw_monero/test/monero_wallet_service_test.dart
  cw_monero/test/utils/setup_monero_c.dart
  lib/entities/seed_type.dart
  lib/monero/cw_monero.dart
  lib/reactions/bip39_wallet_utils.dart
  lib/src/screens/new_wallet/advanced_privacy_settings_page.dart
  lib/src/screens/new_wallet/new_wallet_page.dart
  lib/src/screens/restore/wallet_restore_from_seed_form.dart
  lib/src/screens/restore/wallet_restore_page.dart
  lib/src/widgets/seed_language_picker.dart
  lib/view_model/wallet_groups_display_view_model.dart
  lib/view_model/wallet_keys_view_model.dart
  lib/view_model/wallet_new_vm.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_vi.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
  tool/configure.dart
Labels: Ready for Review

#2122 CW-969-Add-DFX-s-Open-CryptoPay
  cw_evm/lib/evm_chain_client.dart
  cw_monero/lib/api/transaction_history.dart
  lib/core/open_crypto_pay/exceptions.dart
  lib/core/open_crypto_pay/lnurl.dart
  lib/core/open_crypto_pay/models.dart
  lib/core/open_crypto_pay/open_cryptopay_service.dart
  lib/src/screens/send/send_page.dart
  lib/src/screens/send/widgets/send_card.dart
  lib/src/widgets/bottom_sheet/confirm_sending_bottom_sheet_widget.dart
  lib/view_model/send/send_view_model.dart
  res/values/strings_de.arb
Labels: Ready for Review

#2188 Fix missing passphrase for bip39 Monero Wallets
  cw_monero/lib/monero_wallet_service.dart
Labels: Waiting Tests

#2190 fix amount mapping for OCP
  lib/core/open_crypto_pay/open_cryptopay_service.dart
Labels: Ready for Review

#2196 fix: more verbose errors in backups
  lib/view_model/restore_from_backup_view_model.dart
Labels: Ready for Review

#2142 CW-1000 Background sync improvements
  android/app/build.gradle
  android/app/src/main/AndroidManifestBase.xml
  cw_monero/lib/monero_wallet.dart
  cw_shared_external/android/build.gradle
  lib/core/background_sync.dart
  lib/core/wallet_loading_service.dart
  lib/di.dart
  lib/entities/preferences_key.dart
  lib/router.dart
  lib/routes.dart
  lib/src/screens/dev/background_sync_logs_page.dart
  lib/src/screens/dev/shared_preferences_page.dart
  lib/src/screens/settings/background_sync_page.dart
  lib/src/screens/settings/connection_sync_page.dart
  lib/src/screens/settings/other_settings_page.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/dev/background_sync_logs_view_model.dart
  lib/view_model/dev/shared_preferences.dart
  lib/view_model/send/send_view_model.dart
  pubspec_base.yaml
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_vi.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Needs Changes
