Repository cake-tech/cake_wallet, pull requests merged in 2025-03, with the labels that each got.

#1995 Address list fixes CW-883
  lib/src/screens/receive/widgets/address_list.dart
  lib/view_model/wallet_address_list/wallet_address_list_view_model.dart
Labels: Waiting Tests

#2052 Improve bip 353 payment method selection modal
  lib/entities/bip_353_record.dart
  lib/src/widgets/alert_with_picker_option.dart
  lib/src/widgets/base_alert_dialog.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_vi.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Waiting Tests

#2043 CW-924-Don't-prompt-to-save-to-address-book-on-standard-Bitcoin-Litecoin-Bitcoin-Cash-addresses
  lib/core/address_validator.dart
  lib/src/screens/send/send_page.dart
Labels: Waiting Tests

#2045 CW-843: Enhance Wallet Groups Implementation
  .github/workflows/automated_integration_test.yml
  .github/workflows/pr_test_build_android.yml
  .github/workflows/pr_test_build_linux.yml
  cw_bitcoin/lib/bitcoin_wallet_creation_credentials.dart
  cw_bitcoin_cash/lib/src/bitcoin_cash_wallet_creation_credentials.dart
  cw_core/lib/wallet_credentials.dart
  cw_core/lib/wallet_info.dart
  cw_evm/lib/evm_chain_wallet_creation_credentials.dart
  cw_nano/lib/nano_wallet_creation_credentials.dart
  cw_solana/lib/solana_wallet_creation_credentials.dart
  cw_tron/lib/tron_wallet_creation_credentials.dart
  ios/Podfile.lock
  lib/bitcoin/cw_bitcoin.dart
  lib/bitcoin_cash/cw_bitcoin_cash.dart
  lib/core/new_wallet_arguments.dart
  lib/di.dart
  lib/entities/hash_wallet_identifier.dart
  lib/entities/wallet_edit_page_arguments.dart
  lib/entities/wallet_group.dart
  lib/entities/wallet_manager.dart
  lib/ethereum/cw_ethereum.dart
  lib/nano/cw_nano.dart
  lib/polygon/cw_polygon.dart
  lib/reactions/on_current_wallet_change.dart
  lib/solana/cw_solana.dart
  lib/src/screens/new_wallet/wallet_group_display_page.dart
  lib/src/screens/wallet/wallet_edit_page.dart
  lib/src/screens/wallet_list/wallet_list_page.dart
  lib/tron/cw_tron.dart
  lib/view_model/wallet_creation_vm.dart
  lib/view_model/wallet_groups_display_view_model.dart
  lib/view_model/wallet_list/wallet_edit_view_model.dart
  lib/view_model/wallet_new_vm.dart
  tool/configure.dart
  tool/utils/secret_key.dart
Labels: Waiting Tests

#2068 Cw 793 implement kryptonim dfx to fiat buy sell option
  .github/workflows/pr_test_build_android.yml
  .github/workflows/pr_test_build_linux.yml
  assets/images/kryptonim_dark.png
  assets/images/kryptonim_light.png
  lib/buy/buy_provider.dart
  lib/buy/buy_quote.dart
  lib/buy/dfx/dfx_buy_provider.dart
  lib/buy/kryptonim/kryptonim.dart
  lib/buy/meld/meld_buy_provider.dart
  lib/buy/moonpay/moonpay_provider.dart
  lib/buy/onramper/onramper_buy_provider.dart
  lib/buy/payment_method.dart
  lib/di.dart
  lib/entities/provider_types.dart
  lib/view_model/buy/buy_sell_view_model.dart
  tool/utils/secret_key.dart
Labels: Waiting Tests

#2057 CW-983-SwapTrade-enhancements
  lib/entities/default_settings_migration.dart
  lib/exchange/provider/swaptrade_exchange_provider.dart
  lib/exchange/trade_state.dart
  lib/main.dart
  lib/store/dashboard/trade_filter_store.dart
  lib/view_model/dashboard/dashboard_view_model.dart
Labels: Waiting Tests

#2059 CW-949 backup error messages
  lib/view_model/restore_from_backup_view_model.dart
  lib/view_model/wallet_restore_view_model.dart
Labels: Work in Progress

#2055 rename success rate label
  lib/buy/buy_quote.dart
  lib/view_model/buy/buy_sell_view_model.dart
Labels: Waiting Tests

#2040 Cw 855 transactions not cleared correctly when switching wallets
  lib/view_model/dashboard/dashboard_view_model.dart
Labels: Ready for Review

#2050 Cw 940 reduce impossible api calls to trocador
  lib/view_model/exchange/exchange_view_model.dart
Labels: Waiting Tests

#2060 CW-961-Integrate-xoswap
  assets/images/xoswap.svg
  lib/exchange/exchange_provider_description.dart
  lib/exchange/provider/xoswap_exchange_provider.dart
  lib/exchange/trade_state.dart
  lib/src/screens/dashboard/widgets/sync_indicator_icon.dart
  lib/store/dashboard/trade_filter_store.dart
  lib/view_model/dashboard/dashboard_view_model.dart
  lib/view_model/exchange/exchange_trade_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/trade_details_view_model.dart
Labels: Waiting Tests

#2011 Solana Wallet New Implementation
  cw_core/lib/solana_rpc_http_service.dart
  cw_core/pubspec.yaml
  cw_solana/lib/default_spl_tokens.dart
  cw_solana/lib/pending_solana_transaction.dart
  cw_solana/lib/solana_client.dart
  cw_solana/lib/solana_transaction_info.dart
  cw_solana/lib/solana_wallet.dart
  cw_solana/lib/solana_wallet_service.dart
  cw_solana/lib/spl_token.dart
  cw_solana/pubspec.yaml
  cw_tron/pubspec.yaml
  ios/Podfile.lock
  lib/core/wallet_connect/chain_service/solana/solana_chain_service.dart
  lib/core/wallet_connect/web3wallet_service.dart
  lib/solana/cw_solana.dart
  lib/src/screens/wallet_keys/wallet_keys_page.dart
  lib/view_model/advanced_privacy_settings_view_model.dart
  pubspec_base.yaml
  tool/configure.dart
Labels: Waiting Tests

#2036 CW-942-New-Swap-UI-Flow
  integration_test/funds_related_tests.dart
  integration_test/robots/exchange_trade_page_robot.dart
  integration_test/robots/send_page_robot.dart
  lib/di.dart
  lib/router.dart
  lib/routes.dart
  lib/src/screens/exchange/exchange_page.dart
  lib/src/screens/exchange/widgets/present_provider_picker.dart
  lib/src/screens/exchange_trade/exchange_confirm_page.dart
  lib/src/screens/exchange_trade/exchange_trade_external_send_page.dart
  lib/src/screens/exchange_trade/exchange_trade_item.dart
  lib/src/screens/exchange_trade/exchange_trade_page.dart
  lib/src/screens/exchange_trade/widgets/exchange_trade_card_item_widget.dart
  lib/src/screens/send/widgets/send_card.dart
  lib/src/widgets/list_row.dart
  lib/view_model/exchange/exchange_trade_view_model.dart
  lib/view_model/exchange/exchange_view_model.dart
  lib/view_model/send/fees_view_model.dart
  lib/view_model/send/send_view_model.dart
  lib/view_model/transaction_details_view_model.dart
  res/values/strings_ar.arb
  res/values/strings_bg.arb
  res/values/strings_cs.arb
  res/values/strings_de.arb
  res/values/strings_en.arb
  res/values/strings_es.arb
  res/values/strings_fr.arb
  res/values/strings_ha.arb
  res/values/strings_hi.arb
  res/values/strings_hr.arb
  res/values/strings_hy.arb
  res/values/strings_id.arb
  res/values/strings_it.arb
  res/values/strings_ja.arb
  res/values/strings_ko.arb
  res/values/strings_my.arb
  res/values/strings_nl.arb
  res/values/strings_pl.arb
  res/values/strings_pt.arb
  res/values/strings_ru.arb
  res/values/strings_th.arb
  res/values/strings_tl.arb
  res/values/strings_tr.arb
  res/values/strings_uk.arb
  res/values/strings_ur.arb
  res/values/strings_vi.arb
  res/values/strings_yo.arb
  res/values/strings_zh.arb
Labels: Waiting Tests

#1944 Cw 773 restoring from qr gives no visual feedback of progress
  lib/di.dart
  lib/router.dart
  lib/src/screens/restore/restore_options_page.dart
  lib/src/screens/restore/wallet_restore_from_keys_form.dart
  lib/src/screens/restore/wallet_restore_from_seed_form.dart
  lib/src/screens/restore/wallet_restore_page.dart
  lib/src/widgets/seed_widget.dart
  lib/view_model/restore/restore_from_qr_vm.dart
  lib/view_model/restore/wallet_restore_from_qr_code.dart
  lib/view_model/wallet_creation_vm.dart
  lib/view_model/wallet_restore_view_model.dart
Labels: Ready for Review

#1720 open wallet even when cache file backup is corrupted
  cw_monero/lib/monero_wallet_service.dart
Labels: On Hold
